export type ResponseKind = 'item' | 'array' | 'page' | 'action' | 'prewrapped-array' | 'prewrapped-action';

export interface ResponseModel {
  readonly kind: ResponseKind;
  readonly schema?: string;
}

const item = (schema: string): ResponseModel => ({ kind: 'item', schema });
const array = (schema: string): ResponseModel => ({ kind: 'array', schema });
const page = (schema: string): ResponseModel => ({ kind: 'page', schema });
const action: ResponseModel = { kind: 'action' };

export const RELEASE_RESPONSE_MODELS: Readonly<Record<string, ResponseModel>> = {
  AuthController_login: item('LoginData'),
  AuthController_refresh: item('TokenPair'),
  AuthController_me: item('CurrentUser'),
  AuthController_changePassword: action,
  TicketsController_search: page('TicketListItem'),
  TicketsController_create: item('Ticket'),
  TicketsController_findOne: item('Ticket'),
  TicketsController_update: item('Ticket'),
  TicketsController_assign: item('Ticket'),
  TicketsController_reassign: item('Ticket'),
  TicketsController_escalate: item('Ticket'),
  TicketsController_start: item('Ticket'),
  TicketsController_resolve: item('Ticket'),
  TicketsController_close: item('Ticket'),
  TicketsController_reopen: item('Ticket'),
  TicketsController_pendingCustomer: item('Ticket'),
  TicketsController_pendingThirdParty: item('Ticket'),
  TicketsController_history: array('TicketHistory'),
  CommentsController_findAll: page('TicketComment'),
  CommentsController_create: item('TicketComment'),
  CommentsController_update: item('TicketComment'),
  InternalNotesController_findAll: page('InternalNote'),
  InternalNotesController_create: item('InternalNote'),
  InternalNotesController_update: action,
  AttachmentsController_upload: item('Attachment'),
  AttachmentsController_findAllForTicket: page('Attachment'),
  NotificationsController_findAll: page('Notification'),
  NotificationsController_unread: array('Notification'),
  NotificationsController_markRead: action,
  NotificationsController_markAllRead: action,
  DashboardController_overview: item('DashboardOverview'),
  DashboardController_ticketsByStatus: item('DashboardStatusSeries'),
  DashboardController_ticketsByPriority: item('DashboardPrioritySeries'),
  DashboardController_departments: item('DashboardDepartments'),
  DashboardController_slaCompliance: item('DashboardSlaCompliance'),
  DashboardController_workload: item('DashboardWorkload'),
  DashboardController_resolutionTime: item('DashboardResolutionTime'),
  UsersController_findAll: page('User'),
  UsersController_findOne: item('User'),
  UsersController_me: item('User'),
  UsersController_create: item('CreatedUser'),
  UsersController_update: item('User'),
  UsersController_activate: action,
  UsersController_deactivate: action,
  DepartmentsController_findAll: array('Department'),
  DepartmentsController_findOne: item('Department'),
  DepartmentsController_create: item('Department'),
  DepartmentsController_update: item('Department'),
  CategoriesController_findAll: array('Category'),
  CategoriesController_findOne: item('Category'),
  CategoriesController_create: item('Category'),
  CategoriesController_update: item('Category'),
  CategoriesController_remove: action,
  SlaPoliciesController_findAll: array('SlaPolicy'),
  SlaPoliciesController_findOne: item('SlaPolicy'),
  SlaPoliciesController_create: item('SlaPolicy'),
  SlaPoliciesController_update: item('SlaPolicy'),
  AuditLogsController_search: page('AuditLog'),
  AuditLogsController_findOne: item('AuditLog'),
  ReportsController_listReports: page('Report'),
  ReportsController_getReport: item('Report'),
  ReportsController_getTicketReport: item('TicketReport'),
  ReportsController_slaReport: item('SlaReport'),
  ReportsController_ticketReport: item('ReportJob'),
  ReportsController_slaReportAsync: item('ReportJob'),
  ReportsController_weeklyReportAsync: item('ReportJob'),
  SettingsController_getAll: { kind: 'prewrapped-array', schema: 'Setting' },
  SettingsController_update: { kind: 'prewrapped-action' },
};
