/**
 * Codes d'erreur standardisés pour toutes les réponses d'erreur de l'API.
 */
export const ERROR_CODES = {
  // Erreurs de validation
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  INVALID_INPUT: 'INVALID_INPUT',

  // Erreurs d'authentification
  UNAUTHORIZED: 'UNAUTHORIZED',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  TOKEN_EXPIRED: 'TOKEN_EXPIRED',
  TOKEN_INVALID: 'TOKEN_INVALID',
  TOKEN_REVOKED: 'TOKEN_REVOKED',

  // Erreurs d'autorisation
  FORBIDDEN: 'FORBIDDEN',
  INSUFFICIENT_PERMISSIONS: 'INSUFFICIENT_PERMISSIONS',

  // Erreurs de ressources
  NOT_FOUND: 'NOT_FOUND',
  TICKET_NOT_FOUND: 'TICKET_NOT_FOUND',
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  DEPARTMENT_NOT_FOUND: 'DEPARTMENT_NOT_FOUND',

  // Erreurs de conflit
  CONFLICT: 'CONFLICT',
  EMAIL_ALREADY_EXISTS: 'EMAIL_ALREADY_EXISTS',
  DEPARTMENT_NAME_EXISTS: 'DEPARTMENT_NAME_EXISTS',
  DUPLICATE_ENTRY: 'DUPLICATE_ENTRY',

  // Erreurs métier
  INVALID_STATUS_TRANSITION: 'INVALID_STATUS_TRANSITION',
  TICKET_NOT_RESOLVED: 'TICKET_NOT_RESOLVED',
  TICKET_ALREADY_CLOSED: 'TICKET_ALREADY_CLOSED',
  SLA_BREACH: 'SLA_BREACH',

  // Erreurs techniques
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  DATABASE_ERROR: 'DATABASE_ERROR',
  RATE_LIMIT_EXCEEDED: 'RATE_LIMIT_EXCEEDED',
  FILE_TOO_LARGE: 'FILE_TOO_LARGE',
  UNSUPPORTED_MEDIA_TYPE: 'UNSUPPORTED_MEDIA_TYPE',
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
