apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: false
    jsonData:
      timeInterval: 15s
      queryTimeout: 30s
      httpMethod: POST

  - name: Loki
    type: loki
    access: proxy
    url: http://loki:3100
    editable: false
    jsonData:
      maxLines: 1000
      derivedFields:
        # Lie les logs au trace ID Tempo
        - matcherRegex: '"trace_id":"(\w+)"'
          name: traceID
          url: '${__value.raw}'
        # Lie les logs au correlationId
        - matcherRegex: '"correlationId":"([a-zA-Z0-9-]+)"'
          name: correlationId
          url: '${__value.raw}'

  - name: Tempo
    type: tempo
    access: proxy
    url: http://tempo:3200
    editable: false
    jsonData:
      # Service Graph — visualisation des dépendances entre services
      serviceMap:
        datasourceUid: prometheus
      # Recherche via traceID
      tracesToLogsV2:
        datasourceUid: loki
        spanStartTimeShift: '-5m'
        spanEndTimeShift: '5m'
        filterByTraceID: true
        filterBySpanID: true
        tags:
          - key: 'service.name'
            value: telecom-api
          - key: 'correlation.id'
            value: ''
      # Graph de dépendances entre services
      nodeGraph:
        enabled: true
      # Permettre la recherche Loki depuis une trace Tempo
      lokiSearch:
        datasourceUid: loki
      # Recherche de traces par attribut
      search:
        defaultQuery: '{ span.correlation.id ~ ".*" }'
      # Span-to-metrics (génère RED metrics depuis les traces)
      spanMetrics:
        datasourceUid: prometheus
